# Generated by Django 4.2.19 on 2025-03-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=128, verbose_name='名称')),
            ],
            options={
                'verbose_name': '检验代码',
                'verbose_name_plural': '检验代码',
            },
        ),
    ]
