# Generated by Django 4.2.19 on 2025-03-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_order_status'),
        ('Item', '0002_inspectioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(blank=True, help_text='订单', null=True, on_delete=django.db.models.deletion.PROTECT, to='Order.order', verbose_name='订单'),
        ),
        migrations.AddField(
            model_name='item',
            name='parent_item',
            field=models.ForeignKey(blank=True, help_text='上级物品', null=True, on_delete=django.db.models.deletion.PROTECT, to='Item.item', verbose_name='上级物品'),
        ),
    ]
