# Generated by Django 4.2.19 on 2025-03-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_item_order_item_parent_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalchange',
            name='item',
            field=models.ForeignKey(blank=True, help_text='物品', null=True, on_delete=django.db.models.deletion.PROTECT, to='Item.item', verbose_name='物品'),
        ),
    ]
