# Generated by Django 4.2.19 on 2025-03-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0005_item_inspection_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='inspection_codes',
            field=models.ManyToManyField(help_text='检验代码', to='Item.inspectioncode', verbose_name='检验代码'),
        ),
    ]
