# Generated by Django 4.2.19 on 2025-03-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0006_alter_item_inspection_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.IntegerField(default=0, help_text='成本', verbose_name='成本'),
        ),
    ]
