# Generated by Django 4.2.19 on 2025-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0007_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='num',
            field=models.IntegerField(default=1, help_text='数量', verbose_name='数量'),
        ),
    ]
