# Generated by Django 4.2.3 on 2025-03-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0008_item_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='classification',
            field=models.CharField(blank=True, help_text='类别', max_length=128, null=True, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='item',
            name='color_number',
            field=models.CharField(blank=True, help_text='色号', max_length=128, null=True, verbose_name='色号'),
        ),
        migrations.AddField(
            model_name='item',
            name='danieli_standard',
            field=models.CharField(blank=True, help_text='达涅利标准', max_length=128, null=True, verbose_name='达涅利标准'),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='描述', null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='item',
            name='eco_number',
            field=models.CharField(blank=True, help_text='eco数', max_length=128, null=True, verbose_name='eco数'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.CharField(blank=True, help_text='物品编号', max_length=128, null=True, verbose_name='物品编号'),
        ),
        migrations.AddField(
            model_name='item',
            name='jet_position',
            field=models.CharField(blank=True, help_text='工位号', max_length=128, null=True, verbose_name='工位号'),
        ),
        migrations.AddField(
            model_name='item',
            name='line_type',
            field=models.CharField(blank=True, help_text='产线类型', max_length=128, null=True, verbose_name='产线类型'),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, help_text='材料', max_length=128, null=True, verbose_name='材料'),
        ),
        migrations.AddField(
            model_name='item',
            name='paint_type',
            field=models.CharField(blank=True, help_text='油漆种类', max_length=128, null=True, verbose_name='油漆种类'),
        ),
        migrations.AddField(
            model_name='item',
            name='revision',
            field=models.CharField(blank=True, help_text='修订版本', max_length=128, null=True, verbose_name='修订版本'),
        ),
        migrations.AddField(
            model_name='item',
            name='supply_type',
            field=models.CharField(blank=True, help_text='补充类型', max_length=128, null=True, verbose_name='补充类型'),
        ),
        migrations.AddField(
            model_name='item',
            name='uom',
            field=models.CharField(blank=True, help_text='计量单位', max_length=128, null=True, verbose_name='计量单位'),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.IntegerField(blank=True, help_text='重量', null=True, verbose_name='重量'),
        ),
    ]
