# Generated by Django 4.2.3 on 2025-04-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0009_item_classification_item_color_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, help_text='型号', max_length=128, null=True, verbose_name='型号'),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_price',
            field=models.IntegerField(default=0, help_text='销售单价', verbose_name='销售单价'),
        ),
    ]
