# Generated by Django 4.2.3 on 2025-04-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0010_item_model_item_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='packing_number',
            field=models.CharField(blank=True, help_text='箱单号', max_length=128, null=True, verbose_name='箱单号'),
        ),
    ]
