# Generated by Django 4.2.19 on 2025-04-09 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0001_initial'),
        ('Item', '0012_item_pay_money_list_item_receive_goods_date_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contract_number',
            field=models.CharField(blank=True, help_text='合同号', max_length=128, null=True, verbose_name='合同号'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='供应商', null=True, on_delete=django.db.models.deletion.PROTECT, to='Supplier.supplier', verbose_name='供应商'),
        ),
    ]
