# Generated by Django 4.2.19 on 2025-04-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0013_item_contract_number_item_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(choices=[(1, '零件'), (2, '装配')], default=1, help_text='物品类型', verbose_name='物品类型'),
        ),
    ]
