# Generated by Django 4.2.19 on 2025-04-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0014_item_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pay_money_list',
        ),
    ]
