# Generated by Django 4.2.19 on 2025-04-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='名称', max_length=128, null=True, verbose_name='名称')),
                ('contact_person', models.CharField(blank=True, help_text='联系人', max_length=128, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, help_text='电话', max_length=128, null=True, verbose_name='电话')),
                ('email', models.CharField(blank=True, help_text='邮箱', max_length=128, null=True, verbose_name='邮箱')),
                ('tax_number', models.CharField(blank=True, help_text='税号', max_length=128, null=True, verbose_name='税号')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=128, null=True, verbose_name='地址')),
                ('bank_card_number', models.CharField(blank=True, help_text='银行卡号', max_length=128, null=True, verbose_name='银行卡号')),
                ('bank_name', models.CharField(blank=True, help_text='开户行', max_length=128, null=True, verbose_name='开户行')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
    ]
