# Generated by Django 4.2.19 on 2025-04-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Item', '0014_item_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(help_text='数量', verbose_name='数量')),
                ('date', models.DateField(help_text='需求日期', verbose_name='需求日期')),
                ('item', models.ForeignKey(help_text='物品', on_delete=django.db.models.deletion.PROTECT, to='Item.item', verbose_name='物品')),
            ],
            options={
                'verbose_name': '采购需求',
                'verbose_name_plural': '采购需求',
            },
        ),
    ]
