# Generated by Django 4.2.19 on 2025-04-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Item', '0014_item_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain_count', models.IntegerField(help_text='余量', verbose_name='余量')),
                ('operate_log_list', models.JSONField(default=list, help_text='操作记录列表', verbose_name='操作记录列表')),
                ('item', models.ForeignKey(help_text='物品', on_delete=django.db.models.deletion.PROTECT, to='Item.item', verbose_name='物品')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
            },
        ),
    ]
