# Generated by Django 4.2.19 on 2025-03-17 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='记录时间', verbose_name='记录时间')),
                ('action', models.CharField(help_text='动作', max_length=255, verbose_name='动作')),
                ('detail', models.TextField(help_text='详情', verbose_name='详情')),
                ('user', models.ForeignKey(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user', verbose_name='关联的用户')),
            ],
            options={
                'verbose_name': '用户日志',
                'verbose_name_plural': '用户日志',
            },
        ),
    ]
