# Generated by Django 4.2.19 on 2025-03-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(help_text='手机号', max_length=16, verbose_name='手机号')),
                ('password_md5', models.CharField(help_text='密码md5', max_length=128, verbose_name='密码md5')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
