# Generated by Django 4.2.19 on 2025-04-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
        ('Order', '0003_order_collect_money_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(default=1, help_text='负责人', on_delete=django.db.models.deletion.PROTECT, to='UserManagement.user', verbose_name='负责人'),
            preserve_default=False,
        ),
    ]
