# Generated by Django 4.2.19 on 2025-04-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_order_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_start_time',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='交货日期', null=True, verbose_name='交货日期'),
        ),
    ]
