# Generated by Django 4.2.19 on 2025-04-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('Order', '0005_remove_order_order_start_time_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, help_text='客户', on_delete=django.db.models.deletion.PROTECT, to='Customer.customer', verbose_name='客户'),
            preserve_default=False,
        ),
    ]
