# Generated by Django 4.2.19 on 2025-04-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(blank=True, help_text='付款方式', max_length=128, null=True, verbose_name='付款方式'),
        ),
    ]
